/**
 * Zentraler Emoji-Datensatz fuer den EmojiPicker (Dashboard-weit einheitlich).
 *
 * Kategorisierte Standard-Discord-Emojis (Unicode) mit Such-Keywords.
 * Bewusst als statische Liste gebuendelt (keine externe Abhaengigkeit) —
 * deckt die gaengigen Discord-Emojis breit ueber alle Kategorien ab.
 */

export interface EmojiEntry {
  /** Das Emoji-Zeichen (Unicode). */
  e: string;
  /** Leerzeichen-getrennte Such-Keywords (englisch + deutsch). */
  k: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys & Emotion',
    emojis: [
      { e: '😀', k: 'grin smile happy freude lachen' },
      { e: '😃', k: 'smiley happy freude' },
      { e: '😄', k: 'smile happy laugh lachen' },
      { e: '😁', k: 'beaming grin' },
      { e: '😆', k: 'laugh lachen haha' },
      { e: '😅', k: 'sweat smile schwitzen' },
      { e: '🤣', k: 'rofl rolling laughing lachen' },
      { e: '😂', k: 'joy tears laughing lachen traenen' },
      { e: '🙂', k: 'slight smile' },
      { e: '🙃', k: 'upside down' },
      { e: '😉', k: 'wink zwinkern' },
      { e: '😊', k: 'blush smile happy' },
      { e: '😇', k: 'innocent angel engel' },
      { e: '🥰', k: 'love hearts verliebt' },
      { e: '😍', k: 'heart eyes love verliebt' },
      { e: '🤩', k: 'star struck wow' },
      { e: '😘', k: 'kiss kuss' },
      { e: '😗', k: 'kissing' },
      { e: '😚', k: 'kissing closed' },
      { e: '😙', k: 'kissing smile' },
      { e: '😋', k: 'yum tasty lecker' },
      { e: '😛', k: 'tongue zunge' },
      { e: '😜', k: 'wink tongue' },
      { e: '🤪', k: 'zany crazy verrueckt' },
      { e: '😝', k: 'tongue closed eyes' },
      { e: '🤑', k: 'money mouth geld' },
      { e: '🤗', k: 'hug umarmen' },
      { e: '🤭', k: 'hand over mouth' },
      { e: '🤫', k: 'shush quiet leise' },
      { e: '🤔', k: 'thinking nachdenken' },
      { e: '🤐', k: 'zipper mouth' },
      { e: '🤨', k: 'raised eyebrow skeptisch' },
      { e: '😐', k: 'neutral' },
      { e: '😑', k: 'expressionless' },
      { e: '😶', k: 'no mouth' },
      { e: '😏', k: 'smirk' },
      { e: '😒', k: 'unamused genervt' },
      { e: '🙄', k: 'eye roll augen rollen' },
      { e: '😬', k: 'grimace' },
      { e: '🤥', k: 'lying luege' },
      { e: '😌', k: 'relieved erleichtert' },
      { e: '😔', k: 'pensive sad traurig' },
      { e: '😪', k: 'sleepy muede' },
      { e: '🤤', k: 'drooling' },
      { e: '😴', k: 'sleeping schlafen' },
      { e: '😷', k: 'mask maske krank' },
      { e: '🤒', k: 'thermometer sick krank' },
      { e: '🤕', k: 'head bandage verletzt' },
      { e: '🤢', k: 'nauseated uebel' },
      { e: '🤮', k: 'vomit kotzen' },
      { e: '🤧', k: 'sneeze niesen' },
      { e: '🥵', k: 'hot heiss schwitzen' },
      { e: '🥶', k: 'cold kalt frieren' },
      { e: '🥴', k: 'woozy betrunken' },
      { e: '😵', k: 'dizzy schwindelig' },
      { e: '🤯', k: 'mind blown explodieren' },
      { e: '🤠', k: 'cowboy' },
      { e: '🥳', k: 'party feiern celebration' },
      { e: '😎', k: 'sunglasses cool' },
      { e: '🤓', k: 'nerd geek' },
      { e: '🧐', k: 'monocle' },
      { e: '😕', k: 'confused verwirrt' },
      { e: '😟', k: 'worried besorgt' },
      { e: '🙁', k: 'frown' },
      { e: '😮', k: 'open mouth wow' },
      { e: '😯', k: 'hushed' },
      { e: '😲', k: 'astonished schock' },
      { e: '😳', k: 'flushed rot' },
      { e: '🥺', k: 'pleading betteln puppy' },
      { e: '😦', k: 'frowning' },
      { e: '😧', k: 'anguished' },
      { e: '😨', k: 'fearful angst' },
      { e: '😰', k: 'anxious sweat' },
      { e: '😥', k: 'sad relieved' },
      { e: '😢', k: 'cry weinen traurig' },
      { e: '😭', k: 'sob loud cry weinen' },
      { e: '😱', k: 'scream schrei angst' },
      { e: '😖', k: 'confounded' },
      { e: '😣', k: 'persevere' },
      { e: '😞', k: 'disappointed enttaeuscht' },
      { e: '😓', k: 'downcast sweat' },
      { e: '😩', k: 'weary muede' },
      { e: '😫', k: 'tired erschoepft' },
      { e: '🥱', k: 'yawn gaehnen' },
      { e: '😤', k: 'triumph steam' },
      { e: '😡', k: 'rage angry wut' },
      { e: '😠', k: 'angry wut sauer' },
      { e: '🤬', k: 'cursing fluchen' },
      { e: '😈', k: 'devil teufel' },
      { e: '👿', k: 'imp angry devil' },
      { e: '💀', k: 'skull tod dead' },
      { e: '💩', k: 'poop kacke' },
      { e: '🤡', k: 'clown' },
      { e: '👻', k: 'ghost geist' },
      { e: '👽', k: 'alien' },
      { e: '🤖', k: 'robot bot' },
      { e: '😺', k: 'cat smile' },
      { e: '😸', k: 'cat grin' },
      { e: '😻', k: 'cat heart' },
      { e: '🙀', k: 'cat weary' },
      { e: '😹', k: 'cat joy' },
    ],
  },
  {
    id: 'gestures',
    label: 'Gesten & Menschen',
    emojis: [
      { e: '👋', k: 'wave hallo winken' },
      { e: '🤚', k: 'raised back hand' },
      { e: '✋', k: 'raised hand stop' },
      { e: '🖐️', k: 'hand fingers' },
      { e: '👌', k: 'ok okay' },
      { e: '🤌', k: 'pinched italian' },
      { e: '🤏', k: 'pinch small klein' },
      { e: '✌️', k: 'victory peace frieden' },
      { e: '🤞', k: 'crossed fingers glueck' },
      { e: '🤟', k: 'love you' },
      { e: '🤘', k: 'rock horns metal' },
      { e: '🤙', k: 'call me shaka' },
      { e: '👈', k: 'point left links' },
      { e: '👉', k: 'point right rechts' },
      { e: '👆', k: 'point up oben' },
      { e: '👇', k: 'point down unten' },
      { e: '☝️', k: 'index up' },
      { e: '👍', k: 'thumbs up daumen hoch like gut yes ja' },
      { e: '👎', k: 'thumbs down daumen runter dislike no nein' },
      { e: '✊', k: 'fist faust' },
      { e: '👊', k: 'punch faust' },
      { e: '🤛', k: 'left fist' },
      { e: '🤜', k: 'right fist' },
      { e: '👏', k: 'clap applaus klatschen' },
      { e: '🙌', k: 'raising hands hurra' },
      { e: '👐', k: 'open hands' },
      { e: '🤲', k: 'palms together' },
      { e: '🤝', k: 'handshake deal' },
      { e: '🙏', k: 'pray danke bitte please thanks' },
      { e: '✍️', k: 'writing schreiben' },
      { e: '💅', k: 'nail polish' },
      { e: '💪', k: 'muscle stark strong' },
      { e: '🦾', k: 'mechanical arm' },
      { e: '👀', k: 'eyes augen sehen look' },
      { e: '👁️', k: 'eye auge' },
      { e: '🧠', k: 'brain gehirn' },
      { e: '🫀', k: 'heart organ' },
      { e: '👶', k: 'baby' },
      { e: '🧒', k: 'child kind' },
      { e: '👦', k: 'boy junge' },
      { e: '👧', k: 'girl maedchen' },
      { e: '🧑', k: 'person' },
      { e: '👨', k: 'man mann' },
      { e: '👩', k: 'woman frau' },
      { e: '🧔', k: 'beard bart' },
      { e: '👮', k: 'police polizei' },
      { e: '🕵️', k: 'detective spy' },
      { e: '👷', k: 'construction worker' },
      { e: '🤴', k: 'prince prinz' },
      { e: '👸', k: 'princess prinzessin' },
      { e: '🦸', k: 'superhero held' },
      { e: '🦹', k: 'supervillain' },
      { e: '🎅', k: 'santa weihnachtsmann' },
      { e: '🧙', k: 'mage wizard magier' },
      { e: '🧚', k: 'fairy fee' },
      { e: '🧛', k: 'vampire' },
      { e: '🧟', k: 'zombie' },
      { e: '💃', k: 'dancer tanzen' },
      { e: '🕺', k: 'man dancing tanzen' },
      { e: '👯', k: 'bunny ears party' },
      { e: '🏃', k: 'running rennen' },
      { e: '🚶', k: 'walking gehen' },
      { e: '🧎', k: 'kneeling knien' },
    ],
  },
  {
    id: 'nature',
    label: 'Tiere & Natur',
    emojis: [
      { e: '🐶', k: 'dog hund' },
      { e: '🐱', k: 'cat katze' },
      { e: '🐭', k: 'mouse maus' },
      { e: '🐹', k: 'hamster' },
      { e: '🐰', k: 'rabbit hase' },
      { e: '🦊', k: 'fox fuchs' },
      { e: '🐻', k: 'bear baer' },
      { e: '🐼', k: 'panda' },
      { e: '🐨', k: 'koala' },
      { e: '🐯', k: 'tiger' },
      { e: '🦁', k: 'lion loewe' },
      { e: '🐮', k: 'cow kuh' },
      { e: '🐷', k: 'pig schwein' },
      { e: '🐸', k: 'frog frosch' },
      { e: '🐵', k: 'monkey affe' },
      { e: '🐔', k: 'chicken huhn' },
      { e: '🐧', k: 'penguin pinguin' },
      { e: '🐦', k: 'bird vogel' },
      { e: '🦅', k: 'eagle adler' },
      { e: '🦉', k: 'owl eule' },
      { e: '🦇', k: 'bat fledermaus' },
      { e: '🐺', k: 'wolf' },
      { e: '🐗', k: 'boar wildschwein' },
      { e: '🐴', k: 'horse pferd' },
      { e: '🦄', k: 'unicorn einhorn' },
      { e: '🐝', k: 'bee biene' },
      { e: '🐛', k: 'bug wurm' },
      { e: '🦋', k: 'butterfly schmetterling' },
      { e: '🐌', k: 'snail schnecke' },
      { e: '🐞', k: 'ladybug marienkaefer' },
      { e: '🐜', k: 'ant ameise' },
      { e: '🕷️', k: 'spider spinne' },
      { e: '🦂', k: 'scorpion' },
      { e: '🐢', k: 'turtle schildkroete' },
      { e: '🐍', k: 'snake schlange' },
      { e: '🦖', k: 'trex dino' },
      { e: '🐙', k: 'octopus krake' },
      { e: '🦑', k: 'squid' },
      { e: '🦐', k: 'shrimp garnele' },
      { e: '🐠', k: 'fish fisch' },
      { e: '🐬', k: 'dolphin delfin' },
      { e: '🐳', k: 'whale wal' },
      { e: '🦈', k: 'shark hai' },
      { e: '🐊', k: 'crocodile krokodil' },
      { e: '🐅', k: 'tiger' },
      { e: '🦓', k: 'zebra' },
      { e: '🦍', k: 'gorilla' },
      { e: '🐘', k: 'elephant elefant' },
      { e: '🦛', k: 'hippo nilpferd' },
      { e: '🐪', k: 'camel kamel' },
      { e: '🐐', k: 'goat ziege' },
      { e: '🐑', k: 'sheep schaf' },
      { e: '🐕', k: 'dog hund' },
      { e: '🌵', k: 'cactus kaktus' },
      { e: '🌲', k: 'tree baum tanne' },
      { e: '🌳', k: 'tree baum' },
      { e: '🌴', k: 'palm palme' },
      { e: '🌱', k: 'seedling pflanze' },
      { e: '🌿', k: 'herb kraut' },
      { e: '🍀', k: 'clover glueck kleeblatt' },
      { e: '🍁', k: 'maple leaf blatt' },
      { e: '🍂', k: 'fallen leaves herbst' },
      { e: '🌷', k: 'tulip tulpe' },
      { e: '🌹', k: 'rose' },
      { e: '🌸', k: 'blossom bluete' },
      { e: '🌺', k: 'hibiscus blume' },
      { e: '🌻', k: 'sunflower sonnenblume' },
      { e: '🌼', k: 'flower blume' },
      { e: '🌙', k: 'moon mond' },
      { e: '⭐', k: 'star stern' },
      { e: '🌟', k: 'glowing star stern' },
      { e: '✨', k: 'sparkles glitzer funkeln' },
      { e: '⚡', k: 'zap lightning blitz' },
      { e: '🔥', k: 'fire feuer lit hot' },
      { e: '💥', k: 'boom explosion' },
      { e: '❄️', k: 'snowflake schnee' },
      { e: '🌈', k: 'rainbow regenbogen' },
      { e: '☀️', k: 'sun sonne' },
      { e: '⛅', k: 'cloud sun wolke' },
      { e: '☁️', k: 'cloud wolke' },
      { e: '🌊', k: 'wave welle wasser' },
      { e: '💧', k: 'droplet tropfen' },
    ],
  },
  {
    id: 'food',
    label: 'Essen & Trinken',
    emojis: [
      { e: '🍏', k: 'green apple apfel' },
      { e: '🍎', k: 'apple apfel' },
      { e: '🍐', k: 'pear birne' },
      { e: '🍊', k: 'orange' },
      { e: '🍋', k: 'lemon zitrone' },
      { e: '🍌', k: 'banana banane' },
      { e: '🍉', k: 'watermelon melone' },
      { e: '🍇', k: 'grapes trauben' },
      { e: '🍓', k: 'strawberry erdbeere' },
      { e: '🫐', k: 'blueberries' },
      { e: '🍒', k: 'cherries kirsche' },
      { e: '🍑', k: 'peach pfirsich' },
      { e: '🥭', k: 'mango' },
      { e: '🍍', k: 'pineapple ananas' },
      { e: '🥥', k: 'coconut kokos' },
      { e: '🥝', k: 'kiwi' },
      { e: '🍅', k: 'tomato tomate' },
      { e: '🥑', k: 'avocado' },
      { e: '🥦', k: 'broccoli' },
      { e: '🥕', k: 'carrot karotte' },
      { e: '🌽', k: 'corn mais' },
      { e: '🌶️', k: 'pepper chili scharf' },
      { e: '🥔', k: 'potato kartoffel' },
      { e: '🍞', k: 'bread brot' },
      { e: '🥐', k: 'croissant' },
      { e: '🥨', k: 'pretzel brezel' },
      { e: '🧀', k: 'cheese kaese' },
      { e: '🥚', k: 'egg ei' },
      { e: '🍳', k: 'fried egg spiegelei' },
      { e: '🥓', k: 'bacon speck' },
      { e: '🍔', k: 'burger hamburger' },
      { e: '🍟', k: 'fries pommes' },
      { e: '🍕', k: 'pizza' },
      { e: '🌭', k: 'hotdog' },
      { e: '🥪', k: 'sandwich' },
      { e: '🌮', k: 'taco' },
      { e: '🌯', k: 'burrito' },
      { e: '🍝', k: 'spaghetti pasta nudeln' },
      { e: '🍜', k: 'ramen noodles suppe' },
      { e: '🍣', k: 'sushi' },
      { e: '🍤', k: 'shrimp tempura' },
      { e: '🍚', k: 'rice reis' },
      { e: '🍦', k: 'ice cream eis' },
      { e: '🍩', k: 'donut' },
      { e: '🍪', k: 'cookie keks' },
      { e: '🎂', k: 'cake kuchen geburtstag birthday' },
      { e: '🍰', k: 'cake kuchen' },
      { e: '🧁', k: 'cupcake' },
      { e: '🍫', k: 'chocolate schokolade' },
      { e: '🍬', k: 'candy bonbon' },
      { e: '🍭', k: 'lollipop' },
      { e: '🍯', k: 'honey honig' },
      { e: '☕', k: 'coffee kaffee' },
      { e: '🍵', k: 'tea tee' },
      { e: '🥤', k: 'cup drink getraenk' },
      { e: '🍺', k: 'beer bier' },
      { e: '🍻', k: 'beers prost cheers' },
      { e: '🍷', k: 'wine wein' },
      { e: '🥂', k: 'champagne prost' },
      { e: '🍸', k: 'cocktail' },
      { e: '🍾', k: 'champagne bottle' },
    ],
  },
  {
    id: 'activities',
    label: 'Aktivitäten',
    emojis: [
      { e: '⚽', k: 'soccer fussball ball' },
      { e: '🏀', k: 'basketball' },
      { e: '🏈', k: 'football' },
      { e: '⚾', k: 'baseball' },
      { e: '🎾', k: 'tennis' },
      { e: '🏐', k: 'volleyball' },
      { e: '🏉', k: 'rugby' },
      { e: '🎱', k: 'billiard pool 8ball' },
      { e: '🏓', k: 'ping pong tischtennis' },
      { e: '🏸', k: 'badminton' },
      { e: '🥅', k: 'goal tor' },
      { e: '🏒', k: 'hockey' },
      { e: '🏑', k: 'field hockey' },
      { e: '🥊', k: 'boxing boxen' },
      { e: '🥋', k: 'martial arts karate' },
      { e: '⛳', k: 'golf' },
      { e: '🎣', k: 'fishing angeln' },
      { e: '🤿', k: 'diving tauchen' },
      { e: '🎿', k: 'ski' },
      { e: '🛷', k: 'sled schlitten' },
      { e: '🏂', k: 'snowboard' },
      { e: '🏋️', k: 'weight lifting gym fitness' },
      { e: '🤸', k: 'cartwheel' },
      { e: '🤼', k: 'wrestling' },
      { e: '🤾', k: 'handball' },
      { e: '🏌️', k: 'golfing' },
      { e: '🏇', k: 'horse racing' },
      { e: '🧗', k: 'climbing klettern' },
      { e: '🚴', k: 'cycling fahrrad' },
      { e: '🚵', k: 'mountain bike' },
      { e: '🏆', k: 'trophy pokal sieg win gewinner' },
      { e: '🥇', k: 'gold medal erster first' },
      { e: '🥈', k: 'silver medal zweiter' },
      { e: '🥉', k: 'bronze medal dritter' },
      { e: '🏅', k: 'medal medaille' },
      { e: '🎖️', k: 'military medal orden' },
      { e: '🎗️', k: 'ribbon schleife' },
      { e: '🎯', k: 'target dart ziel bullseye' },
      { e: '🎮', k: 'gaming controller spiel game gamer' },
      { e: '🕹️', k: 'joystick arcade' },
      { e: '🎲', k: 'dice wuerfel' },
      { e: '🎰', k: 'slot machine' },
      { e: '🧩', k: 'puzzle' },
      { e: '🎳', k: 'bowling' },
      { e: '🎨', k: 'art palette malen' },
      { e: '🎭', k: 'theater masks masken' },
      { e: '🎤', k: 'microphone mic karaoke singen' },
      { e: '🎧', k: 'headphones kopfhoerer musik' },
      { e: '🎼', k: 'musical score noten' },
      { e: '🎵', k: 'music note musik' },
      { e: '🎶', k: 'music notes musik' },
      { e: '🎹', k: 'piano keyboard' },
      { e: '🥁', k: 'drum trommel' },
      { e: '🎸', k: 'guitar gitarre' },
      { e: '🎺', k: 'trumpet trompete' },
      { e: '🎻', k: 'violin geige' },
      { e: '🎬', k: 'clapper film movie kino' },
      { e: '🎪', k: 'circus zirkus' },
      { e: '🎉', k: 'party tada feiern celebration konfetti' },
      { e: '🎊', k: 'confetti party' },
      { e: '🎈', k: 'balloon ballon' },
      { e: '🎁', k: 'gift geschenk present' },
    ],
  },
  {
    id: 'travel',
    label: 'Reisen & Orte',
    emojis: [
      { e: '🚗', k: 'car auto' },
      { e: '🚕', k: 'taxi' },
      { e: '🚙', k: 'suv' },
      { e: '🚌', k: 'bus' },
      { e: '🏎️', k: 'race car rennwagen' },
      { e: '🚓', k: 'police car polizei' },
      { e: '🚑', k: 'ambulance krankenwagen' },
      { e: '🚒', k: 'fire truck feuerwehr' },
      { e: '🚚', k: 'truck lkw' },
      { e: '🚜', k: 'tractor traktor' },
      { e: '🏍️', k: 'motorcycle motorrad' },
      { e: '🚲', k: 'bicycle fahrrad' },
      { e: '✈️', k: 'airplane flugzeug' },
      { e: '🚀', k: 'rocket rakete boost start' },
      { e: '🛸', k: 'ufo' },
      { e: '🚁', k: 'helicopter hubschrauber' },
      { e: '⛵', k: 'sailboat segelboot' },
      { e: '🚤', k: 'speedboat boot' },
      { e: '🚢', k: 'ship schiff' },
      { e: '⚓', k: 'anchor anker' },
      { e: '🚂', k: 'train zug' },
      { e: '🚆', k: 'train zug' },
      { e: '🚇', k: 'metro ubahn' },
      { e: '🏠', k: 'house haus home' },
      { e: '🏡', k: 'house garden haus' },
      { e: '🏢', k: 'office buero gebaeude' },
      { e: '🏰', k: 'castle schloss burg' },
      { e: '🗼', k: 'tower turm' },
      { e: '🗽', k: 'statue liberty freiheit' },
      { e: '🌍', k: 'earth globe welt europa' },
      { e: '🌎', k: 'earth americas welt' },
      { e: '🌏', k: 'earth asia welt' },
      { e: '🗺️', k: 'map karte' },
      { e: '🧭', k: 'compass kompass' },
      { e: '🏔️', k: 'mountain berg' },
      { e: '🌋', k: 'volcano vulkan' },
      { e: '🏖️', k: 'beach strand' },
      { e: '🏝️', k: 'island insel' },
      { e: '🎡', k: 'ferris wheel riesenrad' },
      { e: '🎢', k: 'roller coaster achterbahn' },
      { e: '🎠', k: 'carousel karussell' },
      { e: '⛲', k: 'fountain brunnen' },
      { e: '🌉', k: 'bridge bruecke' },
      { e: '🗿', k: 'moai statue' },
    ],
  },
  {
    id: 'objects',
    label: 'Objekte',
    emojis: [
      { e: '⌚', k: 'watch uhr' },
      { e: '📱', k: 'phone handy smartphone' },
      { e: '💻', k: 'laptop computer' },
      { e: '⌨️', k: 'keyboard tastatur' },
      { e: '🖥️', k: 'desktop computer pc' },
      { e: '🖨️', k: 'printer drucker' },
      { e: '🖱️', k: 'mouse maus' },
      { e: '💾', k: 'floppy disk save speichern' },
      { e: '💿', k: 'cd disc' },
      { e: '📀', k: 'dvd' },
      { e: '📷', k: 'camera kamera foto' },
      { e: '📸', k: 'camera flash foto' },
      { e: '📹', k: 'video camera' },
      { e: '🎥', k: 'movie camera film' },
      { e: '📺', k: 'tv fernseher' },
      { e: '📻', k: 'radio' },
      { e: '☎️', k: 'phone telefon' },
      { e: '🔋', k: 'battery batterie akku' },
      { e: '🔌', k: 'plug stecker strom' },
      { e: '💡', k: 'bulb idee licht light' },
      { e: '🔦', k: 'flashlight taschenlampe' },
      { e: '🕯️', k: 'candle kerze' },
      { e: '💰', k: 'money bag geld' },
      { e: '💵', k: 'dollar geld cash' },
      { e: '💳', k: 'credit card karte' },
      { e: '💎', k: 'gem diamant' },
      { e: '⚖️', k: 'scale waage balance' },
      { e: '🔧', k: 'wrench schraubenschluessel tool' },
      { e: '🔨', k: 'hammer' },
      { e: '⚙️', k: 'gear zahnrad settings einstellungen' },
      { e: '🛠️', k: 'tools werkzeug' },
      { e: '🔩', k: 'nut bolt schraube' },
      { e: '⛏️', k: 'pick pickaxe' },
      { e: '🧰', k: 'toolbox' },
      { e: '🧲', k: 'magnet' },
      { e: '🔫', k: 'gun waffe pistole' },
      { e: '💣', k: 'bomb' },
      { e: '🔪', k: 'knife messer' },
      { e: '🗡️', k: 'dagger schwert' },
      { e: '⚔️', k: 'swords schwerter kampf' },
      { e: '🛡️', k: 'shield schild schutz' },
      { e: '🔐', k: 'lock key schloss' },
      { e: '🔒', k: 'lock closed geschlossen' },
      { e: '🔓', k: 'lock open offen' },
      { e: '🔑', k: 'key schluessel' },
      { e: '🗝️', k: 'old key schluessel' },
      { e: '🔗', k: 'link kette' },
      { e: '📌', k: 'pushpin pin' },
      { e: '📍', k: 'pin location ort' },
      { e: '📎', k: 'paperclip klammer' },
      { e: '✏️', k: 'pencil stift' },
      { e: '🖊️', k: 'pen kuli' },
      { e: '📝', k: 'memo note notiz schreiben' },
      { e: '📖', k: 'book buch lesen' },
      { e: '📚', k: 'books buecher' },
      { e: '📅', k: 'calendar kalender datum' },
      { e: '📆', k: 'calendar kalender' },
      { e: '📊', k: 'bar chart statistik' },
      { e: '📈', k: 'chart up steigend wachstum' },
      { e: '📉', k: 'chart down fallend' },
      { e: '📋', k: 'clipboard liste' },
      { e: '📁', k: 'folder ordner' },
      { e: '📢', k: 'loudspeaker announce ankuendigung durchsage' },
      { e: '📣', k: 'megaphone' },
      { e: '🔔', k: 'bell glocke benachrichtigung' },
      { e: '🔕', k: 'bell off stumm' },
      { e: '🔊', k: 'speaker laut sound' },
      { e: '📨', k: 'email mail nachricht' },
      { e: '✉️', k: 'envelope brief mail' },
      { e: '📦', k: 'package paket' },
      { e: '🎫', k: 'ticket' },
      { e: '🏷️', k: 'label tag' },
      { e: '💊', k: 'pill pille medizin' },
      { e: '🩹', k: 'bandage pflaster' },
      { e: '🔬', k: 'microscope mikroskop' },
      { e: '🔭', k: 'telescope teleskop' },
      { e: '🧪', k: 'test tube reagenz' },
      { e: '🧬', k: 'dna' },
      { e: '🩺', k: 'stethoscope arzt' },
      { e: '🚽', k: 'toilet klo' },
      { e: '🚿', k: 'shower dusche' },
      { e: '🧹', k: 'broom besen' },
      { e: '🧻', k: 'toilet paper' },
      { e: '🛒', k: 'cart einkaufswagen' },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbole',
    emojis: [
      { e: '❤️', k: 'heart herz love liebe rot red' },
      { e: '🧡', k: 'orange heart herz' },
      { e: '💛', k: 'yellow heart herz gelb' },
      { e: '💚', k: 'green heart herz gruen' },
      { e: '💙', k: 'blue heart herz blau' },
      { e: '💜', k: 'purple heart herz lila' },
      { e: '🖤', k: 'black heart herz schwarz' },
      { e: '🤍', k: 'white heart herz weiss' },
      { e: '🤎', k: 'brown heart herz braun' },
      { e: '💔', k: 'broken heart herz gebrochen' },
      { e: '❣️', k: 'heart exclamation' },
      { e: '💕', k: 'two hearts herzen' },
      { e: '💞', k: 'revolving hearts' },
      { e: '💓', k: 'beating heart' },
      { e: '💗', k: 'growing heart' },
      { e: '💖', k: 'sparkling heart' },
      { e: '💘', k: 'heart arrow amor' },
      { e: '💝', k: 'heart gift geschenk' },
      { e: '💟', k: 'heart decoration' },
      { e: '☮️', k: 'peace frieden' },
      { e: '✝️', k: 'cross kreuz' },
      { e: '☪️', k: 'star crescent islam' },
      { e: '🕉️', k: 'om hindu' },
      { e: '✡️', k: 'star david' },
      { e: '☯️', k: 'yin yang' },
      { e: '⭕', k: 'circle kreis o' },
      { e: '✅', k: 'check green haken done erledigt ja yes accept' },
      { e: '☑️', k: 'checkbox haken' },
      { e: '✔️', k: 'check haken' },
      { e: '❌', k: 'cross x nein no falsch wrong' },
      { e: '❎', k: 'cross mark button' },
      { e: '➕', k: 'plus add hinzufuegen' },
      { e: '➖', k: 'minus remove entfernen' },
      { e: '➗', k: 'divide' },
      { e: '✖️', k: 'multiply x' },
      { e: '♾️', k: 'infinity unendlich' },
      { e: '‼️', k: 'exclamation double' },
      { e: '⁉️', k: 'exclamation question' },
      { e: '❓', k: 'question fragezeichen' },
      { e: '❔', k: 'question white' },
      { e: '❗', k: 'exclamation ausrufezeichen' },
      { e: '⚠️', k: 'warning achtung warnung' },
      { e: '🚫', k: 'no forbidden verboten' },
      { e: '⛔', k: 'no entry stop' },
      { e: '💯', k: 'hundred 100 perfect' },
      { e: '🔞', k: 'no under 18 nsfw' },
      { e: '📵', k: 'no phones' },
      { e: '🔅', k: 'dim brightness' },
      { e: '🔆', k: 'bright brightness' },
      { e: '〽️', k: 'part alternation' },
      { e: '⚜️', k: 'fleur de lis' },
      { e: '🔰', k: 'beginner anfaenger' },
      { e: '♻️', k: 'recycle recycling' },
      { e: '✳️', k: 'asterisk stern' },
      { e: '❇️', k: 'sparkle' },
      { e: '🌐', k: 'globe web internet' },
      { e: '#️⃣', k: 'hash raute' },
      { e: '*️⃣', k: 'asterisk' },
      { e: '0️⃣', k: 'zero null 0' },
      { e: '1️⃣', k: 'one eins 1' },
      { e: '2️⃣', k: 'two zwei 2' },
      { e: '3️⃣', k: 'three drei 3' },
      { e: '4️⃣', k: 'four vier 4' },
      { e: '5️⃣', k: 'five fuenf 5' },
      { e: '6️⃣', k: 'six sechs 6' },
      { e: '7️⃣', k: 'seven sieben 7' },
      { e: '8️⃣', k: 'eight acht 8' },
      { e: '9️⃣', k: 'nine neun 9' },
      { e: '🔟', k: 'ten zehn 10' },
      { e: '🔠', k: 'abcd letters' },
      { e: '🔤', k: 'abc letters' },
      { e: '🆗', k: 'ok' },
      { e: '🆕', k: 'new neu' },
      { e: '🆙', k: 'up' },
      { e: '🆒', k: 'cool' },
      { e: '🆓', k: 'free' },
      { e: '🈵', k: 'no vacancy full' },
      { e: '▶️', k: 'play start' },
      { e: '⏸️', k: 'pause' },
      { e: '⏹️', k: 'stop' },
      { e: '⏭️', k: 'next skip' },
      { e: '⏮️', k: 'previous back' },
      { e: '🔀', k: 'shuffle' },
      { e: '🔁', k: 'repeat loop wiederholen' },
      { e: '🔂', k: 'repeat one' },
      { e: '🔄', k: 'refresh sync aktualisieren' },
      { e: '🔃', k: 'reload' },
      { e: '⬆️', k: 'up arrow oben' },
      { e: '⬇️', k: 'down arrow unten' },
      { e: '⬅️', k: 'left arrow links' },
      { e: '➡️', k: 'right arrow rechts' },
      { e: '↗️', k: 'up right arrow' },
      { e: '↘️', k: 'down right arrow' },
      { e: '🔝', k: 'top oben' },
      { e: '🔙', k: 'back zurueck' },
      { e: '🔛', k: 'on' },
      { e: '🔜', k: 'soon bald' },
      { e: '🔚', k: 'end ende' },
      { e: '💬', k: 'speech bubble chat nachricht' },
      { e: '💭', k: 'thought bubble gedanke' },
      { e: '🗯️', k: 'anger bubble' },
      { e: '♠️', k: 'spades pik' },
      { e: '♥️', k: 'hearts herz' },
      { e: '♦️', k: 'diamonds karo' },
      { e: '♣️', k: 'clubs kreuz' },
      { e: '🃏', k: 'joker' },
      { e: '🎴', k: 'flower cards' },
      { e: '🔴', k: 'red circle rot punkt' },
      { e: '🟠', k: 'orange circle' },
      { e: '🟡', k: 'yellow circle gelb' },
      { e: '🟢', k: 'green circle gruen online' },
      { e: '🔵', k: 'blue circle blau' },
      { e: '🟣', k: 'purple circle lila' },
      { e: '⚫', k: 'black circle schwarz' },
      { e: '⚪', k: 'white circle weiss' },
      { e: '🟤', k: 'brown circle braun' },
      { e: '🟥', k: 'red square rot' },
      { e: '🟧', k: 'orange square' },
      { e: '🟨', k: 'yellow square gelb' },
      { e: '🟩', k: 'green square gruen' },
      { e: '🟦', k: 'blue square blau' },
      { e: '🟪', k: 'purple square lila' },
      { e: '⬛', k: 'black square schwarz' },
      { e: '⬜', k: 'white square weiss' },
    ],
  },
];

/** Flache Liste aller Emojis (fuer Suche). */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap(c => c.emojis);
