from pathlib import Path

p = Path('src/modules/economy/blackMarket.ts')
s = p.read_text(encoding='utf-8')
s = s.replace('''  userDiscordId: string;\n  quantity: number;\n''','''  userDiscordId: string;\n  sourcePocket: EconomyPocket;\n  quantity: number;\n''',1)
s = s.replace("const key = cleanText(external, 96, 'Idempotency-Key');", "const key = cleanText(external, 48, 'Idempotency-Key');",1)
s = s.replace('''  listingId: string; guildId: GuildId; nitradoConnId: NitradoConnId; vendorAccountId: string;\n  userDiscordId: UserDiscordId; quantity: number; unitPrice: bigint; amount: bigint;\n''','''  listingId: string; guildId: GuildId; nitradoConnId: NitradoConnId; vendorAccountId: string;\n  userDiscordId: UserDiscordId; sourcePocket: EconomyPocket; quantity: number;\n''',1)
s = s.replace('''    && row.userDiscordId === String(args.userDiscordId)\n    && row.quantity === args.quantity\n    && row.unitPrice === args.unitPrice\n    && row.amount === args.amount;\n''','''    && row.userDiscordId === String(args.userDiscordId)\n    && row.sourcePocket === args.sourcePocket\n    && row.quantity === args.quantity;\n''',1)
old = '''  if (!Number.isSafeInteger(args.quantity) || args.quantity < 1 || args.quantity > MAX_PER_PURCHASE) throw new Error(`Menge muss zwischen 1 und ${MAX_PER_PURCHASE} liegen.`);\n  await assertEnabled(args.guildId, args.nitradoConnId);\n  const initial = await getMarketListing(args.guildId, args.nitradoConnId, args.listingId);\n  if (!initial || !initial.active || initial.archivedAt) throw new Error('Aktives Listing nicht gefunden.');\n  if (args.quantity > initial.maxPerPurchase) throw new Error(`Pro Kauf sind maximal ${initial.maxPerPurchase} erlaubt.`);\n  const amount = initial.price * BigInt(args.quantity);\n  const key = operationKey(args.listingId, args.idempotencyKey);\n  const replay = await existingPurchase(key);\n  if (replay) {\n    assertPurchaseReplay(replay, { ...args, vendorAccountId: initial.vendorAccountId, unitPrice: initial.price, amount });\n    return { booked: false, purchase: replay, listing: initial };\n  }\n'''
new = '''  if (!Number.isSafeInteger(args.quantity) || args.quantity < 1 || args.quantity > MAX_PER_PURCHASE) throw new Error(`Menge muss zwischen 1 und ${MAX_PER_PURCHASE} liegen.`);\n  const sourcePocket = args.sourcePocket ?? 'WALLET';\n  if (sourcePocket !== 'WALLET' && sourcePocket !== 'BANK') throw new Error('Quellkonto ungueltig.');\n  const key = operationKey(args.listingId, args.idempotencyKey);\n  const replay = await existingPurchase(key);\n  if (replay) {\n    assertPurchaseReplay(replay, { ...args, sourcePocket, vendorAccountId: replay.vendorAccountId });\n    const replayListing = await getMarketListing(args.guildId, args.nitradoConnId, args.listingId);\n    if (!replayListing) throw new Error('Bestaetigter Schwarzmarkt-Kauf ist inkonsistent.');\n    return { booked: false, purchase: replay, listing: replayListing };\n  }\n  await assertEnabled(args.guildId, args.nitradoConnId);\n  const initial = await getMarketListing(args.guildId, args.nitradoConnId, args.listingId);\n  if (!initial || !initial.active || initial.archivedAt) throw new Error('Aktives Listing nicht gefunden.');\n  if (args.quantity > initial.maxPerPurchase) throw new Error(`Pro Kauf sind maximal ${initial.maxPerPurchase} erlaubt.`);\n  const amount = initial.price * BigInt(args.quantity);\n'''
if old not in s: raise SystemExit('buy preamble marker missing')
s = s.replace(old,new,1)
s = s.replace("sourcePocket: args.sourcePocket ?? 'WALLET',", "sourcePocket,",1)
s = s.replace("assertPurchaseReplay(purchases[0], { ...args, vendorAccountId: listing.vendorAccountId, unitPrice: listing.price, amount });", "assertPurchaseReplay(purchases[0], { ...args, sourcePocket, vendorAccountId: listing.vendorAccountId });",1)
s = s.replace('''INSERT INTO "EconomyMarketPurchase" ("id","idempotencyKey","listingId","guildId","nitradoConnId","vendorAccountId","userDiscordId","quantity","unitPrice","amount","createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,CURRENT_TIMESTAMP)'',\n        randomUUID(), key, args.listingId, String(args.guildId), String(args.nitradoConnId), preflight.vendorAccountId,\n        String(args.userDiscordId), args.quantity, preflight.price, amount,''','''INSERT INTO "EconomyMarketPurchase" ("id","idempotencyKey","listingId","guildId","nitradoConnId","vendorAccountId","userDiscordId","sourcePocket","quantity","unitPrice","amount","createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,CURRENT_TIMESTAMP)'',\n        randomUUID(), key, args.listingId, String(args.guildId), String(args.nitradoConnId), preflight.vendorAccountId,\n        String(args.userDiscordId), sourcePocket, args.quantity, preflight.price, amount,''',1)
s = s.replace("assertPurchaseReplay(purchase, { ...args, vendorAccountId: initial.vendorAccountId, unitPrice: initial.price, amount });", "assertPurchaseReplay(purchase, { ...args, sourcePocket, vendorAccountId: purchase.vendorAccountId });",1)
p.write_text(s, encoding='utf-8')

p = Path('src/dashboard/routes/v2/economyBlackMarket.ts')
t = p.read_text(encoding='utf-8')
t = t.replace("if (!raw || raw.length > 96", "if (!raw || raw.length > 32",1)
old = """      quantity: parseIntSafe(req.body?.quantity ?? 1, 'quantity'), sourcePocket: req.body?.sourcePocket === 'BANK' ? 'BANK' : 'WALLET',\n      idempotencyKey: operationKey(req, 'dashboard'),\n"""
new = """      quantity: parseIntSafe(req.body?.quantity ?? 1, 'quantity'),\n      sourcePocket: req.body?.sourcePocket === undefined || req.body?.sourcePocket === 'WALLET' ? 'WALLET' : req.body?.sourcePocket === 'BANK' ? 'BANK' : (() => { throw new Error('sourcePocket muss WALLET oder BANK sein.'); })(),\n      idempotencyKey: operationKey(req, 'dashboard'),\n"""
if old not in t: raise SystemExit('route pocket marker missing')
t=t.replace(old,new,1)
p.write_text(t, encoding='utf-8')

p = Path('prisma/schema.prisma')
u = p.read_text(encoding='utf-8')
u = u.replace('''  @@unique([guildId, nitradoConnId, nameKey], name: "guildServerNameKey", map: "EconomyVirtualAccount_guild_conn_name_key")\n''','''  @@unique([guildId, nitradoConnId, nameKey], name: "guildServerNameKey", map: "EconomyVirtualAccount_guild_conn_name_key")\n  @@unique([id, guildId, nitradoConnId], name: "idScope", map: "EconomyVirtualAccount_id_scope_key")\n''',1)
u = u.replace('''  vendorAccount         EconomyVirtualAccount @relation("MarketVendorListings", fields: [vendorAccountId], references: [id], onDelete: Restrict)\n''','''  vendorAccount         EconomyVirtualAccount @relation("MarketVendorListings", fields: [vendorAccountId, guildId, nitradoConnId], references: [id, guildId, nitradoConnId], onDelete: Restrict)\n''',1)
u = u.replace('''  @@unique([guildId, nitradoConnId, sku], name: "scopeSku", map: "EconomyMarketListing_scope_sku_key")\n''','''  @@unique([guildId, nitradoConnId, sku], name: "scopeSku", map: "EconomyMarketListing_scope_sku_key")\n  @@unique([id, guildId, nitradoConnId], name: "idScope", map: "EconomyMarketListing_id_scope_key")\n''',1)
u = u.replace('''  listing          EconomyMarketListing  @relation(fields: [listingId], references: [id], onDelete: Restrict)\n''','''  listing          EconomyMarketListing  @relation(fields: [listingId, guildId, nitradoConnId], references: [id, guildId, nitradoConnId], onDelete: Restrict)\n''',1)
u = u.replace('''  vendorAccount    EconomyVirtualAccount @relation("MarketVendorPurchases", fields: [vendorAccountId], references: [id], onDelete: Restrict)\n  userDiscordId    String\n  quantity         Int\n''','''  vendorAccount    EconomyVirtualAccount @relation("MarketVendorPurchases", fields: [vendorAccountId, guildId, nitradoConnId], references: [id, guildId, nitradoConnId], onDelete: Restrict)\n  userDiscordId    String\n  sourcePocket     String                @db.VarChar(10)\n  quantity         Int\n''',1)
p.write_text(u, encoding='utf-8')

p = Path('tests/security/economyBlackMarketSafety.test.ts')
v=p.read_text(encoding='utf-8')
v=v.replace("expect(migration).toContain('ON DELETE RESTRICT');", "expect(migration).toContain('EconomyMarketListing_vendor_scope_fkey');\n    expect(migration).toContain('EconomyMarketPurchase_listing_scope_fkey');\n    expect(migration).toContain('ON DELETE RESTRICT');",1)
v=v.replace("expect(migration).toContain('CREATE UNIQUE INDEX \"EconomyMarketPurchase_idempotency_key\"');", "expect(migration).toContain('CREATE UNIQUE INDEX \"EconomyMarketPurchase_idempotency_key\"');\n    expect(migration).toContain('EconomyMarketPurchase_source_pocket_check');",1)
p.write_text(v, encoding='utf-8')
print('black market hardening applied')
