ALTER TYPE "GameplayFeedKind" ADD VALUE IF NOT EXISTS 'PLAYER_LIST';

ALTER TABLE "GameplayFeedConfig"
  ADD COLUMN "nextDeliveryAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "lastMessageId" VARCHAR(32),
  ADD COLUMN "lastStateHash" VARCHAR(64),
  ADD COLUMN "lastPlayerCount" INTEGER,
  ADD COLUMN "lastPlayerListAt" TIMESTAMP(3);
