-- Phase 6E: Erweiterung der AuditCategory um Dashboard-v2-Kategorien.
-- ALTER TYPE ADD VALUE ist idempotent dank IF NOT EXISTS und non-blocking.

ALTER TYPE "AuditCategory" ADD VALUE IF NOT EXISTS 'TICKET';
ALTER TYPE "AuditCategory" ADD VALUE IF NOT EXISTS 'NITRADO';
ALTER TYPE "AuditCategory" ADD VALUE IF NOT EXISTS 'ECONOMY';
ALTER TYPE "AuditCategory" ADD VALUE IF NOT EXISTS 'CASINO';
ALTER TYPE "AuditCategory" ADD VALUE IF NOT EXISTS 'DASHBOARD';
ALTER TYPE "AuditCategory" ADD VALUE IF NOT EXISTS 'WHITELIST';
ALTER TYPE "AuditCategory" ADD VALUE IF NOT EXISTS 'FACTION';
ALTER TYPE "AuditCategory" ADD VALUE IF NOT EXISTS 'SERVER_SETTINGS';
